export const styles = {
    container: {
      maxWidth: "1200px",
      margin: "0 auto",
      padding: "20px",
      background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
      minHeight: "100vh",
      fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
    },
    innerContainer: {
      background: "rgba(255, 255, 255, 0.95)",
      backdropFilter: "blur(10px)",
      borderRadius: "20px",
      padding: "30px",
      boxShadow: "0 20px 40px rgba(0,0,0,0.1)",
    },
    title: {
      textAlign: "center",
      color: "#333",
      marginBottom: "30px",
      fontSize: "2.5em",
      background: "linear-gradient(45deg, #667eea, #764ba2)",
      WebkitBackgroundClip: "text",
      WebkitTextFillColor: "transparent",
      backgroundClip: "text",
      fontWeight: "bold",
    },
    uploadSection: {
      border: "3px dashed #667eea",
      borderRadius: "15px",
      padding: "40px",
      textAlign: "center",
      marginBottom: "30px",
      transition: "all 0.3s ease",
      background:
        "linear-gradient(45deg, rgba(102, 126, 234, 0.1), rgba(118, 75, 162, 0.1))",
      cursor: "pointer",
    },
    uploadSectionHover: {
      borderColor: "#764ba2",
      transform: "translateY(-2px)",
      boxShadow: "0 10px 25px rgba(102, 126, 234, 0.2)",
    },
    uploadSectionDragover: {
      borderColor: "#764ba2",
      background:
        "linear-gradient(45deg, rgba(102, 126, 234, 0.2), rgba(118, 75, 162, 0.2))",
    },
    uploadBtn: {
      background: "linear-gradient(45deg, #667eea, #764ba2)",
      color: "white",
      padding: "15px 30px",
      border: "none",
      borderRadius: "50px",
      cursor: "pointer",
      fontSize: "16px",
      fontWeight: "600",
      transition: "all 0.3s ease",
      boxShadow: "0 5px 15px rgba(102, 126, 234, 0.4)",
    },
    controls: {
      display: "flex",
      gap: "20px",
      alignItems: "center",
      justifyContent: "center",
      marginBottom: "30px",
      flexWrap: "wrap",
    },
    controlGroup: {
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      gap: "10px",
    },
    label: {
      fontWeight: "600",
      color: "#555",
    },
    numberInput: {
      padding: "12px",
      border: "2px solid #ddd",
      borderRadius: "10px",
      fontSize: "16px",
      width: "80px",
      textAlign: "center",
      transition: "border-color 0.3s ease",
    },
    numberInputFocus: {
      outline: "none",
      borderColor: "#667eea",
      boxShadow: "0 0 0 3px rgba(102, 126, 234, 0.1)",
    },
    splitBtn: {
      background: "linear-gradient(45deg, #764ba2, #667eea)",
      color: "white",
      padding: "15px 40px",
      border: "none",
      borderRadius: "50px",
      cursor: "pointer",
      fontSize: "18px",
      fontWeight: "600",
      transition: "all 0.3s ease",
      boxShadow: "0 5px 15px rgba(118, 75, 162, 0.4)",
    },
    splitBtnDisabled: {
      opacity: "0.5",
      cursor: "not-allowed",
    },
    preview: {
      textAlign: "center",
      marginBottom: "30px",
    },
    originalImage: {
      maxWidth: "400px",
      maxHeight: "300px",
      borderRadius: "15px",
      boxShadow: "0 10px 30px rgba(0,0,0,0.2)",
      transition: "transform 0.3s ease",
    },
    puzzleGrid: {
      display: "grid",
      gap: "10px",
      justifyContent: "center",
      marginTop: "30px",
      padding: "20px",
      background: "rgba(255, 255, 255, 0.5)",
      borderRadius: "15px",
    },
    puzzlePiece: {
      borderRadius: "8px",
      boxShadow: "0 5px 15px rgba(0,0,0,0.1)",
      transition: "all 0.3s ease",
      cursor: "pointer",
    },
    downloadAllBtn: {
      background: "linear-gradient(45deg, #28a745, #20c997)",
      color: "white",
      padding: "15px 30px",
      border: "none",
      borderRadius: "50px",
      cursor: "pointer",
      fontSize: "16px",
      fontWeight: "600",
      marginTop: "20px",
      transition: "all 0.3s ease",
      boxShadow: "0 5px 15px rgba(40, 167, 69, 0.4)",
    },
    status: {
      textAlign: "center",
      marginTop: "20px",
      fontWeight: "600",
      color: "#555",
      padding: "15px",
      background: "rgba(102, 126, 234, 0.1)",
      borderRadius: "10px",
    },
  };
